--
-- Create Schema Script 
--   Database Version   : 11.2.0.2.0 
--   TOAD Version       : 9.7.2.5 
--   DB Connect String  : XE 
--   Schema             : IMTG 
--   Script Created by  : IMTG 
--   Script Created at  : 10/10/2016 11:34:57 AM 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 8         Columns: 8          
--   Tables: 12         Columns: 56         Constraints: 21     


CREATE TABLE T_USER
(
  USERID    VARCHAR2(20 BYTE),
  PASSWORD  VARCHAR2(100 BYTE),
  USERTYPE  VARCHAR2(10 BYTE),
  USERNAME  VARCHAR2(20 BYTE),
  GROUPID   INTEGER,
  EMAILID   VARCHAR2(30 BYTE),
  ISACTIVE  INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_TYPE_MASTER
(
  TYPEID    INTEGER,
  TYPENAME  VARCHAR2(20 BYTE),
  ISACTIVE  INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_TYPE_DETAILS
(
  TYPEDETAILSID    INTEGER,
  TYPEID           INTEGER,
  TYPEDETAILSDESC  NVARCHAR2(20),
  ISACTIVE         INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_GROUP
(
  GROUPID    INTEGER,
  GROUPNAME  VARCHAR2(20 BYTE),
  ISACTIVE   INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_DEVICE
(
  USERID    VARCHAR2(20 BYTE),
  DEVICEID  VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_LOCATION
(
  LOCATIONID    INTEGER,
  LOCATIONNAME  VARCHAR2(50 BYTE),
  ISACTIVE      INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_TRAINING
(
  TRAININGID        INTEGER,
  GROUPID           INTEGER,
  USERID            VARCHAR2(20 BYTE),
  TYPEDETAILSID     INTEGER,
  TRAININGDESC      VARCHAR2(100 BYTE),
  LOCATIONID        INTEGER,
  PERIODFROM        DATE,
  PERIODTO          DATE,
  DOCUMENTLOCATION  VARCHAR2(50 BYTE),
  ISACTIVE          INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_MEETING
(
  MEETINGID    INTEGER,
  GROUPID      INTEGER,
  USERID       VARCHAR2(20 BYTE),
  MEETINGDESC  VARCHAR2(100 BYTE),
  MEETINGDATE  DATE,
  DURATION     NUMBER(3,1),
  CHAIR        VARCHAR2(50 BYTE),
  AGENDA       VARCHAR2(100 BYTE),
  ISACTIVE     INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_ATTENDANCE
(
  MEETINGID  INTEGER,
  USERID     VARCHAR2(20 BYTE),
  STATUS     VARCHAR2(1 BYTE)                   DEFAULT 'P'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_SCORING_WINDOW
(
  MEETINGID   INTEGER,
  ISCLOSED    NVARCHAR2(1)                      DEFAULT 'N',
  PERIODFROM  DATE,
  PERIODTO    DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_TOPIC_MASTER
(
  TOPICID    INTEGER,
  TOPIC      VARCHAR2(15 BYTE),
  WEIGHTAGE  INTEGER,
  ISACTIVE   INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE T_SCORING
(
  MEETINGID  INTEGER,
  USERID     VARCHAR2(20 BYTE),
  TOPICID    INTEGER,
  SCORE      NUMBER(3,1)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX T_GROUP_PK ON T_GROUP
(GROUPID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX T_LOCATION_PK ON T_LOCATION
(LOCATIONID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX T_MEETING_PK ON T_MEETING
(MEETINGID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX T_TOPIC_MASTER_PK ON T_TOPIC_MASTER
(TOPICID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX T_TRAINING_PK ON T_TRAINING
(TRAININGID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX T_TYPE_DETAILS_PK ON T_TYPE_DETAILS
(TYPEDETAILSID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX T_TYPE_MASTER_PK ON T_TYPE_MASTER
(TYPEID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX T_USER_PK ON T_USER
(USERID)
LOGGING
NOPARALLEL;


ALTER TABLE T_USER ADD (
  CONSTRAINT T_USER_PK
 PRIMARY KEY
 (USERID));

ALTER TABLE T_TYPE_MASTER ADD (
  CONSTRAINT T_TYPE_MASTER_PK
 PRIMARY KEY
 (TYPEID));

ALTER TABLE T_TYPE_DETAILS ADD (
  CONSTRAINT T_TYPE_DETAILS_PK
 PRIMARY KEY
 (TYPEDETAILSID));

ALTER TABLE T_GROUP ADD (
  CONSTRAINT T_GROUP_PK
 PRIMARY KEY
 (GROUPID));

ALTER TABLE T_LOCATION ADD (
  CONSTRAINT T_LOCATION_PK
 PRIMARY KEY
 (LOCATIONID));

ALTER TABLE T_TRAINING ADD (
  CONSTRAINT T_TRAINING_PK
 PRIMARY KEY
 (TRAININGID));

ALTER TABLE T_MEETING ADD (
  CONSTRAINT T_MEETING_PK
 PRIMARY KEY
 (MEETINGID));

ALTER TABLE T_TOPIC_MASTER ADD (
  CONSTRAINT T_TOPIC_MASTER_PK
 PRIMARY KEY
 (TOPICID));

ALTER TABLE T_USER ADD (
  FOREIGN KEY (GROUPID) 
 REFERENCES T_GROUP (GROUPID));

ALTER TABLE T_TYPE_DETAILS ADD (
  FOREIGN KEY (TYPEID) 
 REFERENCES T_TYPE_MASTER (TYPEID));

ALTER TABLE T_TRAINING ADD (
  FOREIGN KEY (USERID) 
 REFERENCES T_USER (USERID),
  FOREIGN KEY (TYPEDETAILSID) 
 REFERENCES T_TYPE_DETAILS (TYPEDETAILSID),
  FOREIGN KEY (GROUPID) 
 REFERENCES T_GROUP (GROUPID),
  FOREIGN KEY (LOCATIONID) 
 REFERENCES T_LOCATION (LOCATIONID));

ALTER TABLE T_MEETING ADD (
  FOREIGN KEY (USERID) 
 REFERENCES T_USER (USERID),
  FOREIGN KEY (GROUPID) 
 REFERENCES T_GROUP (GROUPID));

ALTER TABLE T_ATTENDANCE ADD (
  FOREIGN KEY (MEETINGID) 
 REFERENCES T_MEETING (MEETINGID));

ALTER TABLE T_SCORING_WINDOW ADD (
  FOREIGN KEY (MEETINGID) 
 REFERENCES T_MEETING (MEETINGID));

ALTER TABLE T_SCORING ADD (
  FOREIGN KEY (USERID) 
 REFERENCES T_USER (USERID),
  FOREIGN KEY (MEETINGID) 
 REFERENCES T_MEETING (MEETINGID),
  FOREIGN KEY (TOPICID) 
 REFERENCES T_TOPIC_MASTER (TOPICID));

